initial Crowd Helm Chart based on Confluence Helm Chart
aservo/atlassian-helm-charts pull request #2
Opened 2021-04-07 17:14 UTC by LouisZschaler

2021-04-08 07:31 UTC, pathob commented
Also ich kann das Chart nicht nutzen, ich versuche Crowd in einer einfachen Config zunächst ohne DB nur mit Ingress zu starten, aber die (interne) Readyness Probe schlägt schon fehl:

```
Events:
  Type     Reason     Age                  From                                    Message
  ----     ------     ----                 ----                                    -------
  Normal   Scheduled  17m                  default-scheduler                       Successfully assigned pr14-crowd/pr14-crowd-0 to aks-pool1-29842438-vmss000000
  Normal   Pulling    17m                  kubelet, aks-pool1-29842438-vmss000000  Pulling image "atlassian/crowd:4.2.2"
  Normal   Pulled     10m                  kubelet, aks-pool1-29842438-vmss000000  Successfully pulled image "atlassian/crowd:4.2.2"
  Normal   Created    10m                  kubelet, aks-pool1-29842438-vmss000000  Created container crowd
  Normal   Started    10m                  kubelet, aks-pool1-29842438-vmss000000  Started container crowd
  Warning  Unhealthy  10m                  kubelet, aks-pool1-29842438-vmss000000  Readiness probe failed: Get http://10.244.0.51:8095/status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  29s (x117 over 10m)  kubelet, aks-pool1-29842438-vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 404
```

2021-04-08 11:41 UTC, borikoss commented
Ich konnte gerade den Crowd-Pod grün bekommen, wenn ich die Healthcheck-URI von **/status** auf **/** setze. Dieser Check kommt so von Confluence als Hard-Code im Template. Ich schätze Crowd deployed /status gar nicht

2021-04-08 12:10 UTC, pathob commented
Danke @borikoss jetzt funzt es, @LouisZschaler du könntest die Änderungen von Boris dann mal in deinen Commit reinziehen (Interactive Rebase, Fixup), dann Force Push und dann sollten wir das vielleicht auch mergen können.

2021-04-08 12:24 UTC, borikoss approved these changes
lgtm

2021-04-08 13:16 UTC, pathob commented
@borikoss Das Approval verfliegt, wenn er den Rebase macht. @LouisZschaler du solltest auch noch die Änderung (letzte Zeile) an der einen Confluence Datei rückgängig machen.

2021-04-15 06:02 UTC, pathob requested changes
Sieht für mich so aus, als gäbe es noch 3 copy-paste Fehler. Den Rest kann ich schwer beurteilen.

2021-04-15 06:02 UTC, pathob commented on src/main/charts/crowd/templates/_fluentd_templates.tpl
> +      value: {{ include "confluence.fullname" . }}
confluence?

2021-04-15 06:02 UTC, pathob commented on src/main/charts/crowd/templates/_fluentd_templates.tpl
> +    name: {{ include "confluence.fullname" . }}-fluentd-config
confluence?

2021-04-15 06:02 UTC, pathob commented on src/main/charts/crowd/templates/statefulset.yaml
> +        # This is intended to ensure that the shared-home volume is group-writeable by the GID used by the Confluence container.
confluence?

2021-05-13 16:49 UTC, closed without merging